--  DIGITAL DAIRY MANAGEMENT SYSTEM — 

-- 1. OWNER
--    Login details for the shop owner. This system is for ONE dairy,
--    so this table normally has just one row, and no other table links to it.
--    password_hash stores a bcrypt hash, never the plain password.
-- ---------------------------------------------------------------------
create table owner (
  owner_id       bigint generated by default as identity primary key,
  name           text        not null,
  shop_name      text        not null,
  username       text        not null unique,
  password_hash  text        not null,
  phone          varchar(15) not null,
  created_at     timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 2. CUSTOMER
--    People who buy milk from the shop. They all belong to the one dairy,
--    so there is no owner_id column.
--    default_rate = usual price per litre, auto-filled on daily entry.
--    is_active = false when a customer stops taking milk (keep history,
--    don't delete).
-- ---------------------------------------------------------------------
create table customer (
  customer_id    bigint generated by default as identity primary key,
  name           text          not null,
  phone          varchar(15),
  address        text,
  milk_type      text          not null default 'cow'
                   check (milk_type in ('cow', 'buffalo')),
  default_rate   numeric(6,2)  not null check (default_rate > 0),
  is_active      boolean       not null default true,
  created_at     timestamptz   not null default now()
);


-- ---------------------------------------------------------------------
-- 3. MILK_RECORD
--    One row per delivery (per customer, per day, per shift).
--    The rate is saved on every row, so old bills stay correct if the
--    price changes later.
--    amount is calculated by the database (quantity × rate), so it can
--    never be miscalculated.
-- ---------------------------------------------------------------------
create table milk_record (
  record_id        bigint generated by default as identity primary key,
  customer_id      bigint        not null references customer(customer_id) on delete cascade,
  record_date      date          not null default current_date,
  shift            text          not null default 'morning'
                     check (shift in ('morning', 'evening')),
  quantity_litres  numeric(5,2)  not null check (quantity_litres > 0),
  rate_per_litre   numeric(6,2)  not null check (rate_per_litre > 0),
  amount           numeric(10,2) generated always as (quantity_litres * rate_per_litre) stored,
  created_at       timestamptz   not null default now(),
  unique (customer_id, record_date, shift)   -- no duplicate entry for the same shift
);


-- ---------------------------------------------------------------------
-- 4. BILL
--    One monthly bill per customer, built by adding up that month's
--    milk records.
--    amount_paid goes up as payments come in.
--    pending_amount is calculated automatically (total − paid).
-- ---------------------------------------------------------------------
create table bill (
  bill_id         bigint generated by default as identity primary key,
  customer_id     bigint        not null references customer(customer_id) on delete cascade,
  bill_month      smallint      not null check (bill_month between 1 and 12),
  bill_year       smallint      not null check (bill_year >= 2000),
  total_litres    numeric(8,2)  not null default 0,
  total_amount    numeric(10,2) not null default 0,
  amount_paid     numeric(10,2) not null default 0 check (amount_paid >= 0),
  pending_amount  numeric(10,2) generated always as (total_amount - amount_paid) stored,
  status          text          not null default 'Pending'
                    check (status in ('Pending', 'Partial', 'Paid')),
  generated_on    date          not null default current_date,
  unique (customer_id, bill_month, bill_year)  -- only one bill per customer per month
);


-- ---------------------------------------------------------------------
-- 5. PAYMENT
--    Money received from a customer against a bill.
--    A bill can have several payments (e.g. ₹1000 now, the rest later).
-- ---------------------------------------------------------------------
create table payment (
  payment_id     bigint generated by default as identity primary key,
  bill_id        bigint        not null references bill(bill_id) on delete cascade,
  customer_id    bigint        not null references customer(customer_id) on delete cascade,
  amount         numeric(10,2) not null check (amount > 0),
  payment_date   date          not null default current_date,
  mode           text          not null default 'cash'
                   check (mode in ('cash', 'upi')),
  note           text
);


-- Indexes on the foreign keys, so "history of customer X" loads quickly
create index idx_milk_customer    on milk_record(customer_id, record_date);
create index idx_bill_customer    on bill(customer_id);
create index idx_payment_bill     on payment(bill_id);
